### ISSUE TITLE
dev/templates files are missing

### ISSUE THREAD

**Issue by PengchongLiu** [qcserenity/serenity#1]
I tried to follow the installation guide, but there seems to be two files missing in the dev/templates folder according to the CMakeLists.txt. 

dev/templates/serenity.sh
dev/templates/test.input

Is there anyway to get around these two file to compile the code?

**Comment by nabbelbabbel** [comment]
Thank for reporting the problem!

Sorry for the inconvenience, that is for sure a mistake I made when cleaning the other templates needed for development purposes only.
I attached the files and I will also update repository.
The files: [dev.zip](https://github.com/qcserenity/serenity/files/3659094/dev.zip)

I will close the issue once the changes are made to the repository.

**Comment by PengchongLiu** [comment]
Thanks a lot!
