### ISSUE TITLE
How to manually set the boost location during compiling?

### ISSUE THREAD

**Issue by wangdu817** [qcserenity/serenity#12]
Hi,
 I just try to install serenity using cmake, it can automatically find the boost installed in the local dir, but I try to set another version of Boost, but the -DBoost_ROOT option is invalid, neither the using the environment variable, how can I set it manually？ Also, how can I skip the gitupdate after the src of libint has been downloaded?

 Thank you
Du Wang

**Comment by TalpaE** [comment]
Hi,
thank you for using Serenity and opening this issue! Have you tried using either the `-DBoost_DIR` or the `-DBoost_INCLUDE_DIR` option?
Regarding the gitupdate of libint: perhaps I am misunderstanding the question, but the libint version currently used in Serenity is not downloaded from the libint GitHub. Instead, a preconfigured version (currently 2.7.0-beta.6) is downloaded from a website of the University of Münster (see `cmake/ImportLibint.cmake`).
