### ISSUE TITLE
Make Fails at 96%

### ISSUE THREAD

**Issue by S-A-WOOD** [qcserenity/serenity#13]
When running make, I get the following issue.

[ 95%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_I_S_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_D.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_D_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_F.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_F_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_G.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_G_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_H.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_H_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_I.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_I_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_P.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_P_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_S.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_P_S_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_D.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_D_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_F.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_F_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_G.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_G_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_H.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_H_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_I.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_I_prereq.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_P.cc.o
[ 96%] Building CXX object ext-libint-build/CMakeFiles/libint2_obj.dir/src/_overlap_S_P_prereq.cc.o
[ 96%] Built target libint2_obj
[ 96%] Linking CXX static library libint2.a
[ 96%] Linking CXX shared library libint2.so
[ 96%] Built target libint2
[ 96%] Built target libint2-static
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/PAOSelection/BoughtonPulayAlgorithm.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/PAOSelection/PNOConstructor.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/PAOSelection/DOIBasedSelector.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/brokenSymmetry/BrokenSymmetry.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/PAOSelection/TNOConstructor.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/brokenSymmetry/CorrespondingOrbitals.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/directOrbitalSelection/DirectOrbitalSelection.cpp.o
In file included from /opt/openmolcas/build/serenity/src/settings/PCMSettings.h:25,
                 from /opt/openmolcas/build/serenity/src/settings/EmbeddingSettings.h:26,
                 from /opt/openmolcas/build/serenity/src/analysis/brokenSymmetry/BrokenSymmetry.h:25,
                 from /opt/openmolcas/build/serenity/src/analysis/brokenSymmetry/BrokenSymmetry.cpp:22:
/opt/openmolcas/build/serenity/src/settings/Reflection.h:49:24: error: 'placeholders' is not a namespace-name; did you mean 'is_placeholder'?
   49 | using namespace boost::placeholders;
      |                        ^~~~~~~~~~~~
      |                        is_placeholder
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/localizationFunctions/ELFCalculator.cpp.o
[ 96%] Building CXX object CMakeFiles/serenity.dir/src/analysis/localizationFunctions/SEDD.cpp.o
In file included from /opt/openmolcas/build/serenity/src/tasks/Task.h:24,
                 from /opt/openmolcas/build/serenity/src/analysis/localizationFunctions/ELFCalculator.h:26,
                 from /opt/openmolcas/build/serenity/src/analysis/localizationFunctions/ELFCalculator.cpp:22:
/opt/openmolcas/build/serenity/src/settings/Reflection.h:49:24: error: 'placeholders' is not a namespace-name; did you mean 'is_placeholder'?
   49 | using namespace boost::placeholders;
      |                        ^~~~~~~~~~~~
      |                        is_placeholder
make[2]: *** [CMakeFiles/serenity.dir/build.make:146: CMakeFiles/serenity.dir/src/analysis/brokenSymmetry/BrokenSymmetry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /opt/openmolcas/build/serenity/src/settings/PCMSettings.h:25,
                 from /opt/openmolcas/build/serenity/src/settings/Settings.h:30,
                 from /opt/openmolcas/build/serenity/src/analysis/localizationFunctions/SEDD.cpp:28:
/opt/openmolcas/build/serenity/src/settings/Reflection.h:49:24: error: 'placeholders' is not a namespace-name; did you mean 'is_placeholder'?
   49 | using namespace boost::placeholders;
      |                        ^~~~~~~~~~~~
      |                        is_placeholder
make[2]: *** [CMakeFiles/serenity.dir/build.make:188: CMakeFiles/serenity.dir/src/analysis/localizationFunctions/ELFCalculator.cpp.o] Error 1
make[2]: *** [CMakeFiles/serenity.dir/build.make:202: CMakeFiles/serenity.dir/src/analysis/localizationFunctions/SEDD.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/serenity.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by TalpaE** [comment]
Which boost version are you using? (CMake tells you at the beginning)
Are you using clang or gcc as C++ compiler? (to check: run `ccmake ..` in the `build` folder, press `t` and look for `CMAKE_CXX_COMPILER`)

**Comment by S-A-WOOD** [comment]
I am using Boost 1.56, and I am using gcc as my C++ compiler.

**Comment by msnik1999** [comment]
Boost 1.56 is pretty old, could you maybe try using Boost 1.66.0?
I would also recommend to continue using gcc.

**Comment by S-A-WOOD** [comment]
Switching to boost 1.66.0 seems to have solved the problem I was having with 1.56.0, but now I am running into a different issue. 

[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/LevelshiftHybridPotential.cpp.o
[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/LevelshiftPotential.cpp.o
[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/NAddFuncPotential.cpp.o
In file included from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/detail/requires_cxx11.hpp:9,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/bind.hpp:24,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:29,
                 from /opt/openmolcas/build/serenity/src/settings/Reflection.h:27,
                 from /opt/openmolcas/build/serenity/src/tasks/LocalizationTask.h:25,
                 from /opt/openmolcas/build/serenity/src/potentials/LevelshiftHybridPotential.cpp:37:
/opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/detail/requires_cxx11.hpp:9,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/bind.hpp:24,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:29,
                 from /opt/openmolcas/build/serenity/src/settings/Reflection.h:27,
                 from /opt/openmolcas/build/serenity/src/settings/PCMSettings.h:25,
                 from /opt/openmolcas/build/serenity/src/settings/Settings.h:30,
                 from /opt/openmolcas/build/serenity/src/potentials/NAddFuncPotential.cpp:41:
/opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/NEInteractionPotential.cpp.o
[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/OptEffPotential.cpp.o
[ 98%] Building CXX object CMakeFiles/serenity.dir/src/potentials/PCMPotential.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/serenity.dir/build.make:3366: CMakeFiles/serenity.dir/src/potentials/CoulombInteractionPotential.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/detail/requires_cxx11.hpp:9,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind/bind.hpp:24,
                 from /opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:29,
                 from /opt/openmolcas/build/serenity/src/settings/Reflection.h:27,
                 from /opt/openmolcas/build/serenity/src/settings/PCMSettings.h:25,
                 from /opt/openmolcas/build/serenity/src/geometry/MolecularSurfaceController.h:27,
                 from /opt/openmolcas/build/serenity/src/potentials/PCMPotential.cpp:28:
/opt/spack/var/spack/environments/base/.spack-env/._view/poa3smiaoe5tjyut5npalwuletwrryen/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/serenity.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by aowen-uwmad** [comment]
I'm helping @S-A-WOOD set up this software.

In the error message is `Please use <boost/bind/bind.hpp> + using namespace boost::placeholders`. From this [stackoverflow thread](https://stackoverflow.com/questions/53203970/why-boostbind-insists-pulling-boostplaceholders-into-global-namespace/65813178#65813178) it seems that the previous include statement was `#include <boost/bind.hpp>`. A quick grep of the repo shows 

```
serenity$ grep -R "boost/bind" *
src/settings/Reflection.h:#include <boost/bind.hpp>
```

I'm going to try swapping out `<boost/bind.hpp>` for `<boost/bind/bind.hpp>` and see if that fixes the issue.

**Comment by TalpaE** [comment]
Did this resolve the issues with compiling?

**Comment by aowen-uwmad** [comment]
Confirmed that this change avoided the error in compiling, and `serenity/bin/serenity --help` printed the splash. I'll let @S-A-WOOD test that the program works as expected, but I didn't see any other errors so I assume it is good now.

```
git clone https://github.com/qcserenity/serenity
cd serenity
sed -i 's|#include <boost/bind.hpp>|#include <boost/bind/bind.hpp>|g' src/settings/Reflection.h
mkdir build
cd build
cmake -DSERENITY_MARCH=native \
    -DSERENITY_PYTHON_BINDINGS=ON \
    -DHDF5ROOT=$(spack location -i hdf5)\
    ..
make -j $NPROC
```
