### ISSUE TITLE
Issue Installing Any Version of Serenity Higher Than 1.4.0

### ISSUE THREAD

**Issue by S-A-WOOD** [qcserenity/serenity#15]
Hello Serenity Folks,

This is a continuation of issue #13 . 

The [attempted fix](https://github.com/qcserenity/serenity/issues/13#issuecomment-2079545484) did result in Serenity 1.6.0 compiling and installing, but it caused a different software [(qcmaquis)](https://github.com/qcscine/qcmaquis) to fail to compile because of a boost related error. We need both qcmaquis and serenity to be installed, but have been unable to get both of them running at the same time. Essentially problem seems that the fix for serenity was to patch it to work with a newer version of boost, but then that in turn requires that qcmaquis be patched to work with a newer version of boost as well. 

We have been able to install serenity 1.4.0, but it does not have the features we need. Any advice for how to proceed? 

For more context, we are trying to install serenity in an [apptainer](https://apptainer.org/) , starting from an ubuntu:20.04 docker. Below is our[ apptainer definition file](https://apptainer.org/docs/user/main/definition_files.html) we used to get serenity 1.4.0 running.

`
Bootstrap: docker
From: ubuntu:20.04

%post -c /bin/bash
    export NPROC=8

    # Update apt
    chmod -R 777 /tmp
    export DEBIAN_FRONTEND=noninteractive
    apt update -y

    # Instal base packages
    apt install -y \
        build-essential \
        ca-certificates \
        coreutils \
        curl \
        debianutils \
        environment-modules \
        gfortran \
        git \
        gpg \
        lsb-release \
        nano \
        python3-pip \
        python3 \
        python3-dev \
        python3-distutils \
        python3-venv \
        tar \
        tree \
        unzip \
        vim \
        ripgrep \
        wget \
        zip \
		libeigen3-dev

    # Installing Spack
    cd /opt
    git clone -c feature.manyFiles=true https://github.com/spack/spack.git
    . /opt/spack/share/spack/setup-env.sh

    # This makes sure that Spack finds the config that is inside of the container itself.
    export SPACK_USER_CONFIG_PATH=/opt/spack/.spack
    echo 'export SPACK_USER_CONFIG_PATH=/opt/spack/.spack' >> $APPTAINER_ENVIRONMENT

    # Install dependencies
    spack env create base
    spack env activate base
    spack add cmake@3.27~doc+ncurses+ownlibs
    spack add gcc-runtime@9.4.0
    spack add gmake@4.4.1~guile
    spack add hdf5@1.12 +cxx +fortran +hl
    spack add boost@1.56 +program_options+filesystem+system+serialization+thread+chrono+date_time+atomic
    spack add openblas@0.3.26~bignuma~consistent_fpcsr+fortran+ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none
    spack add gsl
    spack install -j $NPROC

    ## Install pyparsing
    python3 -m pip install pyparsing==3.1.0
    
    ##install pybind11
    python3 -m pip install pybind11

    # Install OpenMolCAS
    cd /opt
    git clone https://gitlab.com/Molcas/OpenMolcas.git --branch v23.06 openmolcas
    # git clone https://gitlab.com/Molcas/OpenMolcas.git openmolcas
    cd openmolcas
    mkdir build
    cd build
    FC=gfortran CC=gcc CXX=g++ cmake \
        -D LINALG=OpenBLAS \
        -D OPENBLASROOT=$(spack location -i openblas) \
        -D HDF5=ON \
        -D HDF5ROOT=$(spack location -i hdf5) \
        -D DMRG=ON \
        -D NEVPT2=ON \
        ../

    make -j $NPROC
    #echo ">>>Finished making OpenMolcas<<<"
    #{
        #echo "   >>>Attempting to verify<<<"
        #./pymolcas verify &> /opt/pymolcas_verify_results.txt
    #} || {
        #echo ">>> Verification failed <<<"
    #}
    #echo ">>> Verification results are located at /opt/pymolcas_verify_results.txt <<<"

    # Installing autoCAS
    export MOLCAS=/opt/openmolcas/build
    python3 -m pip install scine-autocas

    #INSTALLING serenity
    cd /
    ls
    cd /opt
    ls
    git clone https://github.com/qcserenity/serenity
    
   
    cd serenity
    git checkout 1.4.0

	# Patching v1.4.0 to use the new git location of Libint
    sed -i '13,18d' cmake/ImportLibint.cmake 
    sed -i '13i\    URL https://www.uni-muenster.de/Chemie.oc/THCLAB/libint/libint-2.7.0-beta.6.tgz\n    SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/ext-libint-src' cmake/ImportLibint.cmake

    # This line is for using serenity > 1.5 with boost > 1.6
    # sed -i 's|#include <boost/bind.hpp>|#include <boost/bind/bind.hpp>|g' src/settings/Reflection.h

    mkdir build
    cd build

    cmake -DSERENITY_MARCH=native \
    -DSERENITY_PYTHON_BINDINGS=ON \
    -DHDF5ROOT=$(spack location -i hdf5)\
    ..
    make -j $NPROC
    cd ..
    source serenity.sh
    
	

    # Cleaning up 
    rm -rf /var/lib/apt/lists/*

    # Set up Spack for use in container
    spack gc -y
    spack env deactivate
    spack env activate --sh base >> /opt/spack/environment_modifications.sh
    sed -i 's|PATH=|PATH=/opt/openmolcas/build:/opt/openmolcas/build/bin:/opt/openmolcas/build/sbin:|' /opt/spack/environment_modifications.sh
    cat /opt/spack/environment_modifications.sh >> $APPTAINER_ENVIRONMENT
    echo "export MOLCAS=/opt/openmolcas/build" >> $APPTAINER_ENVIRONMENT
    #cat serenity.sh >> $APPTAINER_ENVIRONMENT
`

Thank You In Advance For Any Help

**Comment by nabbelbabbel** [comment]
Hello,

my first suggestion would be to try and update `serenity` to v1.6.1 rather than 1.6.0 as the patch should fix the download path.

Then for clarification: in the image you base on `ubuntu:20.04` you use `spack` to enforce `boost` v1.56 (`qcmaquis` compliant ) which breaks `serenity` or you install a version of `boost` that is compliant with `serenity` and that breaks `qcmaquis`.

Could you please report the errors you see when using a newer version of boost that aligns with `serenity` and the try to compile `qcmaquis` into that same environment?
The docs for `qcmaquis` request `boost>=1.56` hence I would think that should be the correct way of doing it.
Also, I do remember making both these codes work on the same machine with something like boost v1.73 on Centos7 a few years back.

Best,
Jan

**Comment by S-A-WOOD** [comment]
Hello Jan,

It seems that using boost 1.73.0 got both serenity and qcmaquis running. Thank you so much for the help, and in case it is helpful to anyone else I have included the apptainer definition file below. 

`
Bootstrap: docker
From: ubuntu:20.04

%post -c /bin/bash
    export NPROC=8

    # Update apt
    chmod -R 777 /tmp
    export DEBIAN_FRONTEND=noninteractive
    apt update -y

    # Instal base packages
    apt install -y \
        build-essential \
        ca-certificates \
        coreutils \
        curl \
        debianutils \
        environment-modules \
        gfortran \
        git \
        gpg \
        lsb-release \
        nano \
        python3-pip \
        python3 \
        python3-dev \
        python3-distutils \
        python3-venv \
        tar \
        tree \
        unzip \
        vim \
        ripgrep \
        wget \
        zip \
		libeigen3-dev



    # Installing Spack
    cd /opt
    git clone -c feature.manyFiles=true https://github.com/spack/spack.git
    . /opt/spack/share/spack/setup-env.sh

    # This makes sure that Spack finds the config that is inside of the container itself.
    export SPACK_USER_CONFIG_PATH=/opt/spack/.spack
    echo 'export SPACK_USER_CONFIG_PATH=/opt/spack/.spack' >> $APPTAINER_ENVIRONMENT

    # Install dependencies
    spack env create base
    spack env activate base
    spack add cmake@3.27~doc+ncurses+ownlibs
    spack add gcc-runtime@9.4.0
    spack add gmake@4.4.1~guile
    spack add hdf5@1.12 +cxx +fortran +hl
    spack add boost@1.73.0 +program_options+filesystem+system+serialization+thread+chrono+date_time+atomic
    spack add openblas@0.3.26~bignuma~consistent_fpcsr+fortran+ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none
    spack add gsl
    # spack add serenity +python
    spack install -j $NPROC

    ## Install pyparsing
    python3 -m pip install pyparsing==3.1.0
    
    ##install pybind11
    python3 -m pip install pybind11


    # Install OpenMolCAS
    cd /opt
    git clone https://gitlab.com/Molcas/OpenMolcas.git --branch v23.06 openmolcas
    # git clone https://gitlab.com/Molcas/OpenMolcas.git openmolcas
    cd openmolcas
    mkdir build
    cd build
    FC=gfortran CC=gcc CXX=g++ cmake \
        -D LINALG=OpenBLAS \
        -D OPENBLASROOT=$(spack location -i openblas) \
        -D HDF5=ON \
        -D HDF5ROOT=$(spack location -i hdf5) \
        -D DMRG=ON \
        -D NEVPT2=ON \
        ../

    make -j $NPROC
    #echo ">>>Finished making OpenMolcas<<<"
    #{
        #echo "   >>>Attempting to verify<<<"
        #./pymolcas verify &> /opt/pymolcas_verify_results.txt
    #} || {
        #echo ">>> Verification failed <<<"
    #}
    #echo ">>> Verification results are located at /opt/pymolcas_verify_results.txt <<<"

    # Installing autoCAS
    export MOLCAS=/opt/openmolcas/build
    python3 -m pip install scine-autocas

    #INSTALLING serenity
    cd /
    ls
    cd /opt
    ls
    git clone https://github.com/qcserenity/serenity
    
   
    cd serenity
    sed -i 's|#include <boost/bind.hpp>|#include <boost/bind/bind.hpp>|g' src/settings/Reflection.h

    mkdir build
    cd build

    cmake -DSERENITY_MARCH=native \
    -DSERENITY_PYTHON_BINDINGS=ON \
    -DHDF5ROOT=$(spack location -i hdf5)\
    ..
    make -j $NPROC
    cd ..
    source serenity.sh
    
	

    # Cleaning up 
    rm -rf /var/lib/apt/lists/*

    # Set up Spack for use in container
    spack gc -y
    spack env deactivate
    spack env activate --sh base >> /opt/spack/environment_modifications.sh
    sed -i 's|PATH=|PATH=/opt/openmolcas/build:/opt/openmolcas/build/bin:/opt/openmolcas/build/sbin:|' /opt/spack/environment_modifications.sh
    cat /opt/spack/environment_modifications.sh >> $APPTAINER_ENVIRONMENT
    echo "export MOLCAS=/opt/openmolcas/build" >> $APPTAINER_ENVIRONMENT
    #cat serenity.sh >> $APPTAINER_ENVIRONMENT
`

Thanks,
SAW
