### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by manassharma07** [qcserenity/serenity#2]
When running make I get the following error

[  4%] Building CXX object CMakeFiles/serenity.dir/src/analysis/localizationFunctions/ELFCalculator.cpp.o
In file included from /home/manas/serenity-master/src/io/HDF5.h:28:0,
                 from /home/manas/serenity-master/src/data/matrices/SPMatrix.h:22,
                 from /home/manas/serenity-master/src/data/matrices/MatrixInBasis.h:24,
                 from /home/manas/serenity-master/src/integrals/OneElectronIntegralController.h:25,
                 from /home/manas/serenity-master/src/integrals/OneIntControllerFactory.h:23,
                 from /home/manas/serenity-master/src/system/SystemController.h:25,
                 from /home/manas/serenity-master/src/analysis/localizationFunctions/ELFCalculator.h:25,
                 from /home/manas/serenity-master/src/analysis/localizationFunctions/ELFCalculator.cpp:22:
/home/manas/serenity-master/src/io/Eigen3HDF5.h: In function ‘void Serenity::EigenHDF5::save(H5::H5Location&, const string&, const Eigen::EigenBase<Derived>&, const H5::DSetCreatPropList&)’:
/home/manas/serenity-master/src/io/Eigen3HDF5.h:420:35: error: ‘class H5::H5Location’ has no member named ‘createDataSet’; did you mean ‘createAttribute’?
     H5::DataSet dataset = h5group.createDataSet(name.c_str(), *datatype, dataspace, plist);
                                   ^~~~~~~~~~~~~
                                   createAttribute
/home/manas/serenity-master/src/io/Eigen3HDF5.h: In function ‘void Serenity::EigenHDF5::load(const H5::H5Location&, const string&, const Eigen::DenseBase<Derived>&)’:
/home/manas/serenity-master/src/io/Eigen3HDF5.h:601:41: error: ‘const class H5::H5Location’ has no member named ‘openDataSet’
     const H5::DataSet dataset = h5group.openDataSet(name.c_str());
                                         ^~~~~~~~~~~
/home/manas/serenity-master/src/io/Eigen3HDF5.h: In function ‘void Serenity::EigenHDF5::save_sparse(H5::H5Location&, const string&, const SparseMatrixType&, const H5::DSetCreatPropList&)’:
/home/manas/serenity-master/src/io/Eigen3HDF5.h:671:35: error: ‘class H5::H5Location’ has no member named ‘createDataSet’; did you mean ‘createAttribute’?
     H5::DataSet dataset = h5group.createDataSet(name, *datatype, dataspace, plist);
                                   ^~~~~~~~~~~~~
                                   createAttribute
/home/manas/serenity-master/src/io/Eigen3HDF5.h: In function ‘void Serenity::EigenHDF5::load_sparse(const H5::H5Location&, const string&, SparseMatrixType&)’:
/home/manas/serenity-master/src/io/Eigen3HDF5.h:684:41: error: ‘const class H5::H5Location’ has no member named ‘openDataSet’
     const H5::DataSet dataset = h5group.openDataSet(name);
                                         ^~~~~~~~~~~
In file included from /home/manas/serenity-master/src/data/matrices/SPMatrix.h:22:0,
                 from /home/manas/serenity-master/src/data/matrices/MatrixInBasis.h:24,
                 from /home/manas/serenity-master/src/integrals/OneElectronIntegralController.h:25,
                 from /home/manas/serenity-master/src/integrals/OneIntControllerFactory.h:23,
                 from /home/manas/serenity-master/src/system/SystemController.h:25,
                 from /home/manas/serenity-master/src/analysis/localizationFunctions/ELFCalculator.h:25,
                 from /home/manas/serenity-master/src/analysis/localizationFunctions/ELFCalculator.cpp:22:
/home/manas/serenity-master/src/io/HDF5.h: In function ‘void Serenity::HDF5::save_attribute(H5::H5File, const string&, const T&) [with T = std::__cxx11::basic_string<char>; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/manas/serenity-master/src/io/HDF5.h:199:42: error: no matching function for call to ‘save_scalar_attribute(H5::H5File&, const string&, const string&)’
   save_scalar_attribute(file, name, value);

**Comment by nabbelbabbel** [comment]
Hi Manas Sharma

At first glance this looks like a wrong version of the HDF5 library is loaded.
Can you please check that the HDF5 version is 1.10.1 or above.

Seeing that you did the configure step you can check the `CMakeCache.txt` in your build folder.
In that file `HDF5_DIR` or similar variables will show which version (path) is actually loaded.

**Comment by manassharma07** [comment]
Hi Jan Unsleber,

Thanks for the quick response. That seems to have been it.
I had 1.10.0 before. 

Now the compilation seems to be going further. Will let you know if I face any other problem.

Thanks again!
