### ISSUE TITLE
How are electron-electron interactions between the two subsystems calculated?

### ISSUE THREAD

**Issue by manassharma07** [qcserenity/serenity#3]
It seems to me that even when `densityFitting RI` flag is provided for a system block, SERENITY still calculates the inter subsystem electronic interaction using 4c2e (no density fitting) rather than the expected density fitting.

Is what I suspect true?

If so, then is there a way to calculate the inter subsystem electronic interactions using the density of active subsystem and the auxiliary density of the environment subsystem.

**Comment by nabbelbabbel** [comment]
Closing stale issue.
