### ISSUE TITLE
Compilation Error with GNU on MacOS

### ISSUE THREAD

**Issue by SoulokeSen** [qcserenity/serenity#5]
Dear Developers,

I tried to compile the source code on Mac with standard MKL/GNU compilers. I get the following error relating to 'malloc.h' header

/Users/souloke/Programs/serenity/src/data/OrbitalPairSet.cpp:27:10: fatal error: 'malloc.h' file not found
#include <malloc.h> //Free unused memory.
         ^~~~~~~~~~
On looking up the issue it seemd malloc.h is deprecated and instead some propositions were to use 
#include <stdlib.h>

However, that still didnt work, because now, the compiler couldnt find the function malloc_trim()

/Users/souloke/Programs/serenity/src/data/OrbitalPairSet.cpp:58:3: error: use of undeclared identifier 'malloc_trim'
  malloc_trim(0);

Could you please suggest how to resolve this ?

**Comment by moritzBens** [comment]
It is rather difficult for us to test the compilation on Mac OS regularly because we do not have access to a Mac.

It looks like `malloc_trim(...)` is not easily available under Mac OS. The easiest solution would be to remove all `#include <malloc.h>` statements and all `malloc_trim` calls in the code. This will make the memory handling for the local coupled cluster slightly worse. Other parts of the code should not be affected and the performance difference for the local coupled cluster should only be small.

**Comment by SoulokeSen** [comment]
Okay, thanks for the tip, but now i have a different issue, not sure if its related to the compiler or Mac:

/Users/souloke/Programs/serenity/src/potentials/bundles/FDEPotentials.cpp:38:3: error: no match for 'operator!' (operand type is 'std::vector<std::shared_ptr<Serenity::NAddFuncPotential<Serenity::Options::SCF_MODES::RESTRICTED> >, std::allocator<std::shared_ptr<Serenity::NAddFuncPotential<Serenity::Options::SCF_MODES::RESTRICTED> > > >')
   38 |   assert(_naddXC);

Any ideas what might be causing this ? (P.S. : I am not that proficient in C++, so its a bit diffcult for me to debug )

thanks,
Souloke

**Comment by moritzBens** [comment]
You are probably compiling in Debug mode. Try changing to Release (use `ccmake ..` to adjust the build options or use `cmake -DCMAKE_BUILD_TYPE=Release ..` to execute cmake) and recompile.
This is a bug. We will fix it. Alternatively, you can delete lines 38-39 of `src/potentials/bundles/FDEPotentials.cpp`.

**Comment by SoulokeSen** [comment]
Another similar issue, should i also comment it out for now ?

/Users/souloke/Programs/serenity/src/integrals/wrappers/Libint.cpp:235:14: error: no match for 'operator==' (operand types are 'Serenity::LIBINT_OPERATOR' and 'libint2::Operator')
  235 |   assert((op == libint2::Operator::emultipole1 || op == libint2::Operator::emultipole2) &&
      |           ~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by moritzBens** [comment]
Asserts shouldn't be compiled when building in Release mode. But, yes removing it will work.

**Comment by SoulokeSen** [comment]
Working for Linux at the moment !

On a separate Note : Is there a python wrapper class for LRSCFTask (akin to the SCFTask) ?

thanks,
Souloke

**Comment by moritzBens** [comment]
Great!

No, sadly there is no python wrapper for the LRSCFTask yet.

Best,
Moritz

**Comment by moritzBens** [comment]
The Python wrapper for the LRSCFTask was introduced in Serenity 1.5.0 and Serenity should now compile properly again on MacOS (tested for Apple M1 Pro, Serenity 1.5.2).

I think this addresses all problems raised in this issue.
